#!/usr/bin/env bash

# ----------------------------------------------------------------------------
# bash_profile is executed for login shells
# while bashrc is executed for interactive non-login shells
# ----------------------------------------------------------------------------

# Source .bashrc
if [ -f $HOME/.bashrc ]; then
  source $HOME/.bashrc
fi
