#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status.
set -e

# Set local variables
plist_filename="com.googlecode.iterm2.plist"
saved_plist_path="$DOTFILES_HOME/modules/iterm2/$plist_filename"
installed_plist_path="$HOME/Library/Preferences/$plist_filename"

# Functions
log()   { printf -- "--> $*\n" ; return $? ; }
warn()  { printf -- "--> $*\n" ; return $? ; }

if [[ "$TERM_PROGRAM" == "iTerm.app" ]] ; then
  warn "You appear to be running this script from within iTerm.app which could"
  warn "overwrite your new preferences on quit. Please quit iTerm and run this"
  warn "from Terminal.app or an SSH session."
  exit 1
fi

if ps wwwaux | grep -q 'iTerm\.app' >/dev/null ; then
  warn "You appear to have iTerm.app currently running. Please quit the"
  warn "application so your updates won't get overridden on quit."
  exit 2
fi

if [[ $? -eq 0 ]] ; then
  cp -f "$saved_plist_path" "$installed_plist_path"
  log "iTerm preferences restored to: $installed_plist_path"
else
  warn "Your iTerm preferences have not been changed."
  exit 3
fi

exit $?
