#!/usr/bin/env bash

# ------------------------------------------------------------------------------
# Find all `.symlink` files in $DOTFILES_HOME and symlink them in $HOME
#
# Requires: readlink, dirname, ln, find
#
# TODO: add support for installing to a different directory
# TODO: add the --uninstall flag and have uninstaller use this script
# TODO: support --force to delete existing target files
# ------------------------------------------------------------------------------

# Initialize local variables
this_dir="$(dirname $0)"
find_root=`dirname "${this_dir}"`
find_name="*.symlink"

# Find all `.symlink` files in $DOTFILES_HOME and symlink them in $HOME
while read -d '' src_path; do

  # Extract filename without `.symlink` extension
  target_filename=`basename "${src_path}"`
  target_filename_without_ext="${target_filename%.*}"
  target_path="${HOME}/.${target_filename_without_ext}"

  # If target already exists
  if [ -e "${target_path}" ]; then
    echo "[WARNING] Already exists: ${target_path}"

  # If target doesn't exist yet, create symlink
  else
    echo "[SUCCESS] Symlinking: ${target_path} -> ${src_path}"
    ln -s "${src_path}" "${target_path}" </dev/null
  fi

done < <(find "${find_root}" -iname "${find_name}" -print0)
