#!/usr/bin/env bash
#
# TODO: add support for installing to a different directory
# TODO: add the --uninstall flag and have uninstaller use this script
# TODO: make this use an array and a loop
# TODO: automatically find all .symlink files

# bash
ln -s ~/.dotfiles/bash/bash_profile.symlink ~/.bash_profile
ln -s ~/.dotfiles/bash/bashrc.symlink ~/.bashrc

# git
ln -s ~/.dotfiles/modules/git/gitignore.symlink ~/.gitignore

# screen
ln -s ~/.dotfiles/modules/screen/screenrc.symlink ~/.screenrc

# ruby
ln -s ~/.dotfiles/modules/ruby/bundle.symlink/ ~/.bundle
ln -s ~/.dotfiles/modules/ruby/gemrc.symlink ~/.gemrc
ln -s ~/.dotfiles/modules/ruby/irbrc.symlink ~/.irbrc
ln -s ~/.dotfiles/modules/ruby/pryrc.symlink ~/.pryrc
ln -s ~/.dotfiles/modules/ruby/rspec.symlink ~/.rspec

# node
ln -s ~/.dotfiles/modules/node/npmrc.symlink ~/.npmrc

# vim
#ln -s ~/.dotfiles/modulesvim/vim.symlink/ ~/.vim
#ln -s ~/.dotfiles/modulesvim/vimrc.symlink ~/.vimrc
#ln -s ~/.dotfiles/modulesvim/gvimrc.symlink ~/.gvimrc
#ln -s ~/.dotfiles/modulesvim/mvimrc.symlink ~/.mvimrc
