#!/usr/bin/env bash

# ------------------------------------------------------------------------------
# Find all `.symlink` files in $DOTFILES_HOME and unlink them in $HOME
#
# TODO: consolidate this functionality into the symlinks-install command
# ------------------------------------------------------------------------------

# Initialize local variables
this_dir="$(dirname $0)"
find_root=`dirname "${this_dir}"`
find_name="*.symlink"

# Find all `.symlink` files in $DOTFILES_HOME and symlink them in $HOME
while read -d '' src_path; do

  # Extract filename without `.symlink` extension
  target_filename=`basename "${src_path}"`
  target_filename_without_ext="${target_filename%.*}"
  target_path="${HOME}/.${target_filename_without_ext}"

  # If target symlink already exists, unlink
  if [ -h "${target_path}" ]; then
    echo "[SUCCESS] Unlinking: ${target_path}"
    unlink "${target_path}"

  # If target doesn't exist yet
  else
    echo "[FAILURE] Symlink missing: ${target_path}"
  fi

done < <(find "${find_root}" -iname "${find_name}" -print0)
