#!/usr/bin/env bash

# TODO: instead, run install-symlinks command with an --uninstall flag

# bash
unlink ~/.bash_profile
unlink ~/.bashrc

# git
unlink ~/.gitignore

# screen
unlink ~/.screenrc

# ruby
unlink ~/.bundle
unlink ~/.gemrc
unlink ~/.irbrc
unlink ~/.pryrc
unlink ~/.rspec

# node
unlink ~/.npmrc

# vim
unlink ~/.vim
unlink ~/.vimrc
unlink ~/.gvimrc
unlink ~/.mvimrc
